import { browserStartHelper, browserStopHelper } from "./browser-helper.js";
import { type BrowserHelperInput, browserHelperSessionKeys } from "./browser-helper-types.js";

export type IabBrowserHelperInput = BrowserHelperInput & {
  mailboxRoot: string;
};

const registryName = "recordly.codex.iab-helper.v1";
const eventMethods = [
  "Page.screencastFrame",
  "Runtime.consoleAPICalled",
  "Page.frameNavigated",
] as const;

function sharedAdapterSource(input: IabBrowserHelperInput): string[] {
  return [
    'import { randomUUID } from "node:crypto";',
    'import { lstat, readFile, rename, unlink, writeFile } from "node:fs/promises";',
    'import { join } from "node:path";',
    `const registryKey = Symbol.for(${JSON.stringify(registryName)});`,
    "const registry = globalThis[registryKey] ?? new Map();",
    "globalThis[registryKey] = registry;",
    `const recordingSessionId = ${JSON.stringify(input.sessionId)};`,
    `const recordingOrigin = ${JSON.stringify(input.origin)};`,
    `const brokerEndpoint = ${JSON.stringify(input.endpoint)};`,
    `const mailboxRoot = ${JSON.stringify(input.mailboxRoot)};`,
    `const eventMethods = ${JSON.stringify(eventMethods)};`,
    "const wait = (milliseconds) => new Promise((resolveWait) => setTimeout(resolveWait, milliseconds));",
    "const postJson = async (url, options) => {",
    "  const parsed = new URL(url);",
    "  if (parsed.origin !== new URL(brokerEndpoint).origin || parsed.username !== '' || parsed.password !== '') throw new Error('recordly IAB broker endpoint is invalid');",
    "  const id = randomUUID();",
    "  const requestPath = join(mailboxRoot, 'request-' + id + '.json');",
    "  const temporaryPath = requestPath + '.tmp';",
    "  const responsePath = join(mailboxRoot, 'response-' + id + '.json');",
    "  const token = options.headers?.['x-recordly-capability'];",
    "  const serialized = JSON.stringify({ schemaVersion: 1, id, path: parsed.pathname, ...(token === undefined ? {} : { token }), data: options.data });",
    "  if (Buffer.byteLength(serialized) > 9 * 1024 * 1024) throw new Error('recordly IAB broker request is too large');",
    "  try {",
    "    await writeFile(temporaryPath, serialized, { mode: 0o600, flag: 'wx' });",
    "    await rename(temporaryPath, requestPath);",
    "    const deadline = Date.now() + 10000;",
    "    while (Date.now() < deadline) {",
    "      try {",
    "        const status = await lstat(responsePath);",
    "        if (!status.isFile() || status.isSymbolicLink() || status.size > 65536) throw new Error('recordly IAB broker response is invalid');",
    "        const response = JSON.parse(await readFile(responsePath, 'utf8'));",
    "        await unlink(responsePath);",
    "        if (!Number.isSafeInteger(response.status) || response.body === null || typeof response.body !== 'object') throw new Error('recordly IAB broker response is invalid');",
    "        return { ok: () => response.status >= 200 && response.status < 300, json: async () => response.body };",
    "      } catch (error) {",
    "        if (error?.code !== 'ENOENT') throw error;",
    "      }",
    "      await wait(5);",
    "    }",
    "    throw new Error('recordly IAB broker request timed out');",
    "  } finally {",
    "    await Promise.all([unlink(temporaryPath).catch(() => undefined), unlink(requestPath).catch(() => undefined), unlink(responsePath).catch(() => undefined)]);",
    "  }",
    "};",
    "const createPage = async (tab) => {",
    "  const initialUrl = await tab.url();",
    "  if (typeof initialUrl !== 'string' || initialUrl.length === 0) throw new Error('recordly IAB tab URL is unavailable');",
    '  const cdp = await tab.capabilities.get("cdp");',
    "  const initial = await cdp.readEvents({ methods: eventMethods, limit: 1, timeoutMs: 1 });",
    "  let cursor = initial.cursor;",
    "  let active = true;",
    "  let pumpError;",
    "  let consecutiveReadFailures = 0;",
    "  let cdpOperationTail = Promise.resolve();",
    "  const withCdp = async (work) => {",
    "    const previous = cdpOperationTail;",
    "    let release;",
    "    cdpOperationTail = new Promise((resolveOperation) => { release = resolveOperation; });",
    "    await previous;",
    "    try { return await work(); } finally { release(); }",
    "  };",
    "  const listeners = new Map(eventMethods.map((method) => [method, new Set()]));",
    "  const pump = (async () => {",
    "    while (active) {",
    "      let batch;",
    "      try { batch = await withCdp(() => cdp.readEvents({ afterSequence: cursor, methods: eventMethods, limit: 1000, timeoutMs: 25 })); consecutiveReadFailures = 0; }",
    "      catch { consecutiveReadFailures += 1; if (consecutiveReadFailures > 10) throw new Error('recordly IAB CDP event read failed'); await wait(10); continue; }",
    "      cursor = batch.cursor;",
    "      if (batch.truncated) throw new Error('recordly IAB CDP event stream was truncated');",
    "      for (const event of batch.events) {",
    "        const targets = listeners.get(event.method);",
    "        if (targets === undefined) continue;",
    "        for (const listener of targets) listener(event.params ?? {});",
    "      }",
    "    }",
    "  })().catch((error) => { pumpError = error; active = false; });",
    "  const session = {",
    "    send: async (method, params = {}) => {",
    "      if (pumpError !== undefined) throw pumpError;",
    "      return await withCdp(() => cdp.send(method, params));",
    "    },",
    "    on: (method, listener) => { const targets = listeners.get(method); if (targets === undefined) throw new Error('recordly IAB CDP event method is unsupported'); targets.add(listener); },",
    "    off: (method, listener) => { listeners.get(method)?.delete(listener); },",
    "    detach: async () => {",
    "      active = false;",
    "      await pump;",
    "      if (pumpError !== undefined) throw pumpError;",
    "    },",
    "  };",
    "  const page = {",
    "    url: () => initialUrl,",
    "    context: () => ({ newCDPSession: async () => session }),",
    "    waitForTimeout: wait,",
    "    request: {",
    "      post: postJson,",
    "    },",
    "  };",
    "  return { tab, page, session };",
    "};",
  ];
}

/** Emits a private ESM entrypoint for the real Codex in-app Browser tab-scoped CDP capability. */
export function iabBrowserStartHelper(input: IabBrowserHelperInput): string {
  const legacyStart = browserStartHelper(input).trim();
  const stateKey = browserHelperSessionKeys(input.sessionId).stateKey;
  return [
    ...sharedAdapterSource(input),
    `const startCapture = ${legacyStart};`,
    "const captureActions = (runtime) => {",
    `  const stateKey = ${JSON.stringify(stateKey)};`,
    "  const capture = runtime.page[stateKey];",
    "  if (capture === undefined || capture.recordingSessionId !== recordingSessionId) throw new Error('recordly IAB capture state is unavailable');",
    "  let actionTail = Promise.resolve();",
    "  const runAction = async (work) => {",
    "    const previous = actionTail;",
    "    let release;",
    "    actionTail = new Promise((resolveAction) => { release = resolveAction; });",
    "    await previous;",
    "    try {",
    "      if (capture.state.active !== true || capture.state.observedFailed === true) throw new Error('recordly IAB capture is not active');",
    "      return await work();",
    "    } finally { release(); }",
    "  };",
    "  const postObserved = async (event) => {",
    "    await capture.post('/observed-event', { sessionId: recordingSessionId, origin: recordingOrigin, event }, capture.state.token);",
    "  };",
    "  const clickSelector = async (selector) => await runAction(async () => {",
    "    if (typeof selector !== 'string' || selector.length === 0 || selector.length > 512 || /[\\u0000-\\u001f\\u007f]/u.test(selector)) throw new Error('recordly IAB click selector is invalid');",
    "    const expression = '(() => { const selector = ' + JSON.stringify(selector) + '; let matches; try { matches = document.querySelectorAll(selector); } catch { return { error: \"invalid\" }; } if (matches.length !== 1) return { error: \"count\" }; const element = matches[0]; const style = getComputedStyle(element); const rect = element.getBoundingClientRect(); if (style.visibility === \"hidden\" || style.display === \"none\" || Number(style.opacity) === 0 || rect.width <= 0 || rect.height <= 0) return { error: \"hidden\" }; const x = rect.left + rect.width / 2; const y = rect.top + rect.height / 2; if (!Number.isFinite(x) || !Number.isFinite(y) || x < 0 || y < 0 || x >= innerWidth || y >= innerHeight) return { error: \"outside\" }; const target = document.elementFromPoint(x, y); if (target === null || (target !== element && !element.contains(target))) return { error: \"occluded\" }; return { x, y }; })()';",
    "    const evaluated = await runtime.session.send('Runtime.evaluate', { expression, awaitPromise: false, returnByValue: true });",
    "    if (evaluated?.exceptionDetails !== undefined) throw new Error('recordly IAB click selector evaluation failed');",
    "    const point = evaluated?.result?.value;",
    "    if (point === null || typeof point !== 'object' || Object.keys(point).length !== 2 || !Number.isFinite(point.x) || !Number.isFinite(point.y)) throw new Error('recordly IAB click target must resolve to one visible unobscured element');",
    "    await runtime.session.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: point.x, y: point.y, button: 'none', buttons: 0 });",
    "    await runtime.session.send('Input.dispatchMouseEvent', { type: 'mousePressed', x: point.x, y: point.y, button: 'left', buttons: 1, clickCount: 1 });",
    "    try {",
    "      await runtime.session.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: point.x, y: point.y, button: 'left', buttons: 0, clickCount: 1 });",
    "    } catch (error) {",
    "      await runtime.session.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: point.x, y: point.y, button: 'left', buttons: 0, clickCount: 1 }).catch(() => undefined);",
    "      throw error;",
    "    }",
    "    await postObserved({ type: 'click', data: { x: point.x, y: point.y, button: 0 } });",
    "    return { x: point.x, y: point.y, button: 0 };",
    "  });",
    "  const readScroll = async () => {",
    "    const evaluated = await runtime.session.send('Runtime.evaluate', { expression: '({ x: scrollX, y: scrollY, width: innerWidth, height: innerHeight })', awaitPromise: false, returnByValue: true });",
    "    if (evaluated?.exceptionDetails !== undefined) throw new Error('recordly IAB scroll position evaluation failed');",
    "    const position = evaluated?.result?.value;",
    "    if (position === null || typeof position !== 'object' || !Number.isFinite(position.x) || !Number.isFinite(position.y) || !Number.isFinite(position.width) || !Number.isFinite(position.height) || position.width <= 0 || position.height <= 0) throw new Error('recordly IAB scroll position is unavailable');",
    "    return position;",
    "  };",
    "  const scrollBy = async (input) => await runAction(async () => {",
    "    const deltaX = input?.deltaX ?? 0;",
    "    const deltaY = input?.deltaY ?? 0;",
    "    if (!Number.isFinite(deltaX) || !Number.isFinite(deltaY) || (deltaX === 0 && deltaY === 0) || Math.abs(deltaX) > 100000 || Math.abs(deltaY) > 100000) throw new Error('recordly IAB scroll delta is invalid');",
    "    const before = await readScroll();",
    "    const clientX = before.width / 2;",
    "    const clientY = before.height / 2;",
    "    await runtime.session.send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: clientX, y: clientY, deltaX, deltaY });",
    "    let after = before;",
    "    for (let attempt = 0; attempt < 120; attempt += 1) {",
    "      await wait(16);",
    "      after = await readScroll();",
    "      if (after.x !== before.x || after.y !== before.y) break;",
    "    }",
    "    const actualDeltaX = after.x - before.x;",
    "    const actualDeltaY = after.y - before.y;",
    "    if (actualDeltaX === 0 && actualDeltaY === 0) throw new Error('recordly IAB scroll position did not change');",
    "    const event = { type: 'scroll', data: { x: after.x, y: after.y, deltaX: actualDeltaX, deltaY: actualDeltaY } };",
    "    await postObserved(event);",
    "    return event.data;",
    "  });",
    "  return { clickSelector, scrollBy };",
    "};",
    "export default async function startRecordlyIabCapture(tab) {",
    "  if (registry.has(recordingSessionId)) throw new Error('recordly IAB capture already started');",
    "  const runtime = await createPage(tab);",
    "  registry.set(recordingSessionId, runtime);",
    "  try {",
    "    const started = await startCapture(runtime.page);",
    "    return { ...started, actions: captureActions(runtime) };",
    "  } catch (error) {",
    "    registry.delete(recordingSessionId);",
    "    await runtime.session.detach().catch(() => undefined);",
    "    throw error;",
    "  }",
    "}",
    "",
  ].join("\n");
}

/** Emits the matching stop entrypoint; it cannot operate on a different tab or session. */
export function iabBrowserStopHelper(input: IabBrowserHelperInput): string {
  const legacyStop = browserStopHelper(input).trim();
  return [
    ...sharedAdapterSource(input),
    `const stopCapture = ${legacyStop};`,
    "export default async function stopRecordlyIabCapture(tab) {",
    "  const runtime = registry.get(recordingSessionId);",
    "  if (runtime === undefined || runtime.tab !== tab) throw new Error('recordly IAB capture is not active on this tab');",
    "  try {",
    "    return await stopCapture(runtime.page);",
    "  } finally {",
    "    registry.delete(recordingSessionId);",
    "    await runtime.session.detach();",
    "  }",
    "}",
    "",
  ].join("\n");
}
