type BrowserHelperInput = {
  sessionId: string;
  endpoint: string;
  origin: string;
};

function requestCode(input: BrowserHelperInput): string {
  return [
    `const endpoint = ${JSON.stringify(input.endpoint)};`,
    `const recordingSessionId = ${JSON.stringify(input.sessionId)};`,
    `const recordingOrigin = ${JSON.stringify(input.origin)};`,
    "const post = async (path, body, token) => {",
    `  const response = await page.request.post(\`\${endpoint}\${path}\`, {`,
    "    headers: token === undefined ? { 'content-type': 'application/json' } : { 'content-type': 'application/json', 'x-recordly-capability': token },",
    "    data: body,",
    "  });",
    "  const result = await response.json();",
    "  if (!response.ok() || result.ok !== true) throw new Error('recordly capture broker rejected request');",
    "  return result;",
    "};",
  ].join("\n");
}

/** Generates a Browser-runner function snippet: no imports, filesystem, process, or model paths. */
export function browserStartHelper(input: BrowserHelperInput): string {
  const stateKey = `__recordlyCapture_${input.sessionId}`;
  const worldName = `recordly-observed-${input.sessionId}`;
  const cleanupKey = `__recordlyCleanup_${input.sessionId}`;
  const pointerFlushKey = `__recordlyFlushPointer_${input.sessionId}`;
  return [
    "async (page) => {",
    requestCode(input),
    `  const stateKey = ${JSON.stringify(stateKey)};`,
    `  const worldName = ${JSON.stringify(worldName)};`,
    `  const cleanupKey = ${JSON.stringify(cleanupKey)};`,
    `  const pointerFlushKey = ${JSON.stringify(pointerFlushKey)};`,
    "  if (page[stateKey] !== undefined) throw new Error('recordly capture already started');",
    "  const claim = await post('/claim', { sessionId: recordingSessionId, url: page.url() });",
    "  const token = claim.token;",
    "  if (typeof token !== 'string') throw new Error('recordly capture claim failed');",
    "  const session = await page.context().newCDPSession(page);",
    "  const state = { active: true, receivedFrames: 0, acceptedFrames: 0, ackedFrames: 0, rejectedFrames: 0, degraded: false, pending: [], observedPending: [], observedFailed: false, observedReady: false, token };",
    "  let observedContextId; let observationGeneration = 0; let observationTail = Promise.resolve(); let observationArmed = false; let targetObservedDocument; let committedObserved; let observedReadiness; let observedEpoch = 0; let observedScope; const activeObservedContexts = new Set(); const retiredObservedContexts = new Set();",
    "  let initialObservedSettled = false; let resolveInitialObserved; let rejectInitialObserved;",
    "  const initialObservedReady = new Promise((resolve, reject) => { resolveInitialObserved = resolve; rejectInitialObserved = reject; });",
    "  void initialObservedReady.catch(() => undefined);",
    "  const resolveInitialReady = () => { if (!initialObservedSettled) { initialObservedSettled = true; resolveInitialObserved(); } };",
    "  const rejectInitialReady = (error) => { if (!initialObservedSettled) { initialObservedSettled = true; rejectInitialObserved(error); } };",
    "  const replaceObservedScope = (identity) => { observedScope = { epoch: ++observedEpoch, identity, marker: undefined, pinnedNonce: undefined, evalDone: false, readyHandshake: false }; return observedScope; };",
    "  const retireActiveObserved = () => { for (const contextId of activeObservedContexts) retiredObservedContexts.add(contextId); activeObservedContexts.clear(); };",
    "  const failObserved = (error) => { state.observedFailed = true; state.observedReady = false; committedObserved = undefined; replaceObservedScope(undefined); retireActiveObserved(); state.active = false; rejectInitialReady(error instanceof Error ? error : new Error(String(error))); };",
    "  const boundedTeardown = async (work) => {",
    "    return await Promise.race([Promise.resolve().then(work), page.waitForTimeout(250).then(() => undefined)]);",
    "  };",
    "  const observedBinding = async (event) => {",
    "    if (!state.active) return;",
    "    const task = post('/observed-event', { sessionId: recordingSessionId, origin: recordingOrigin, event }, state.token)",
    "      .then(() => undefined)",
    "      .catch((error) => { failObserved(error); throw error; });",
    "    state.observedPending.push(task);",
    "    try { await task; } finally { state.observedPending = state.observedPending.filter((item) => item !== task); }",
    "  };",
    "  const staleExecutionContext = (error) => /(?:cannot find context with specified id|execution context was destroyed)/iu.test(error instanceof Error ? error.message : String(error));",
    "  const cleanupObserved = async (contextId) => {",
    "    if (!Number.isSafeInteger(contextId)) return;",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emits the isolated-world cleanup key serialization.
    "    const expression = `(() => { const cleanup = globalThis[${JSON.stringify(cleanupKey)}]; if (typeof cleanup === 'function') cleanup(); })()`;",
    "    await session.send('Runtime.evaluate', { expression, contextId, awaitPromise: false, returnByValue: true });",
    "  };",
    "  const flushObserved = async (contextId) => {",
    "    if (!Number.isSafeInteger(contextId)) return;",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emits the isolated-world pointer-flush key serialization.
    "    const expression = `(() => { const flush = globalThis[${JSON.stringify(pointerFlushKey)}]; if (typeof flush === 'function') flush(); })()`;",
    "    await session.send('Runtime.evaluate', { expression, contextId, awaitPromise: false, returnByValue: true });",
    "  };",
    "  const retireObserved = (contextId) => { if (Number.isSafeInteger(contextId)) retiredObservedContexts.add(contextId); };",
    "  const cleanupRetiredObserved = async () => {",
    "    const contextIds = [...retiredObservedContexts]; retiredObservedContexts.clear();",
    "    for (const contextId of contextIds) { try { await cleanupObserved(contextId); } catch (error) { if (!staleExecutionContext(error)) throw error; } }",
    "  };",
    "  const frameDocument = (frame) => typeof frame?.id === 'string' && frame.id.trim() !== '' && typeof frame.loaderId === 'string' && frame.loaderId.trim() !== '' && typeof frame.url === 'string' && frame.url.trim() !== '' && typeof frame.securityOrigin === 'string' && frame.securityOrigin.trim() !== '' && frame.securityOrigin === recordingOrigin ? { frameId: frame.id, loaderId: frame.loaderId, documentUrl: frame.url } : undefined;",
    "  const sameDocument = (left, right) => left !== undefined && right !== undefined && left.frameId === right.frameId && left.loaderId === right.loaderId;",
    "  const observationCurrent = (readiness) => state.active && readiness === observedReadiness && readiness.generation === observationGeneration;",
    "  const beginObservedGeneration = () => {",
    "    const generation = ++observationGeneration; state.observedReady = false; committedObserved = undefined;",
    "    let settled = false; let resolveReady; const promise = new Promise((resolve) => { resolveReady = resolve; });",
    "    const readiness = { generation, promise, resolve: () => { if (!settled) { settled = true; resolveReady(); } } };",
    "    observedReadiness = readiness; return readiness;",
    "  };",
    "  const queueObservation = (work) => { const task = observationTail.then(work); observationTail = task.catch(() => undefined); return task; };",
    "  const commitObservedReady = (document, readiness, scope, executionContextId) => {",
    "    if (!observationCurrent(readiness) || observedScope !== scope || scope.evalDone !== true || scope.readyHandshake !== true || typeof scope.pinnedNonce !== 'string') return;",
    "    observedContextId = executionContextId; committedObserved = { document, generation: readiness.generation, ready: true }; state.observedReady = true; readiness.resolve(); resolveInitialReady();",
    "  };",
    "  const installObserved = async (document, readiness, scope) => {",
    "    const scopeCurrent = () => state.active && observedScope === scope && scope.identity === document;",
    "    let challenge; try { challenge = await post('/observer-challenge', { sessionId: recordingSessionId, origin: recordingOrigin, documentEpoch: scope.epoch, documentUrl: document.documentUrl }, state.token); } catch (error) { if (!scopeCurrent()) return; throw error; }",
    "    if (!scopeCurrent()) return;",
    "    const marker = challenge.marker;",
    "    if (typeof marker !== 'string' || !/^[0-9a-f]{64}$/u.test(marker)) throw new Error('recordly observer challenge unavailable');",
    "    scope.marker = marker;",
    "    let world; try { world = await session.send('Page.createIsolatedWorld', { frameId: document.frameId, worldName, grantUniveralAccess: false }); } catch (error) { if (!scopeCurrent()) return; throw error; }",
    "    if (!Number.isSafeInteger(world.executionContextId)) throw new Error('recordly isolated world unavailable');",
    "    const executionContextId = world.executionContextId;",
    "    if (!scopeCurrent()) { retireObserved(executionContextId); await cleanupRetiredObserved(); return; }",
    "    const expression = `(() => {",
    "      const nonceBytes = new Uint8Array(32); crypto.getRandomValues(nonceBytes);",
    "      const nonce = Array.from(nonceBytes, (byte) => byte.toString(16).padStart(2, '0')).join('');",
    `      const debug = console.debug.bind(console); const prior = globalThis[\${JSON.stringify(cleanupKey)}]; if (typeof prior === 'function') prior();`,
    "      let lastX = window.scrollX; let lastY = window.scrollY; let wheelScheduled = false; let wheelAttempts = 0; let wheelRaf; let wheelTimer;",
    "      let pointerPending; let pointerRaf; let pointerTimer; let lastPointerSentAt = -Infinity;",
    `      const send = (event) => debug(\${JSON.stringify(marker)}, JSON.stringify({ kind: 'event', nonce, event }));`,
    "      const click = (event) => { if (event.isTrusted) send({ type: 'click', data: { x: event.clientX, y: event.clientY, button: event.button } }); };",
    "      const emitPointer = () => { pointerRaf = undefined; pointerTimer = undefined; const event = pointerPending; pointerPending = undefined; if (event === undefined) return; const elapsed = performance.now() - lastPointerSentAt; if (elapsed < 33) { pointerPending = event; pointerTimer = setTimeout(emitPointer, Math.ceil(33 - elapsed)); return; } lastPointerSentAt = performance.now(); send({ type: 'pointer', data: { x: event.x, y: event.y, buttons: event.buttons, cursor: event.buttons === 0 ? 'default' : 'pressed' } }); };",
    "      const pointer = (event) => { if (!event.isTrusted || !Number.isFinite(event.clientX) || !Number.isFinite(event.clientY) || !Number.isSafeInteger(event.buttons) || event.buttons < 0 || event.buttons > 31) return; pointerPending = { x: event.clientX, y: event.clientY, buttons: event.buttons }; if (pointerRaf === undefined && pointerTimer === undefined) pointerRaf = requestAnimationFrame(emitPointer); };",
    "      const flushPointer = () => { if (pointerRaf !== undefined) cancelAnimationFrame(pointerRaf); if (pointerTimer !== undefined) clearTimeout(pointerTimer); pointerRaf = undefined; pointerTimer = undefined; if (pointerPending !== undefined) { lastPointerSentAt = -Infinity; emitPointer(); } };",
    `      const settleWheel = () => { wheelRaf = requestAnimationFrame(() => { const x = window.scrollX; const y = window.scrollY; const deltaX = x - lastX; const deltaY = y - lastY; if (deltaX !== 0 || deltaY !== 0) { wheelScheduled = false; lastX = x; lastY = y; debug(\${JSON.stringify(marker)}, JSON.stringify({ kind: 'event', nonce, event: { type: 'scroll', data: { x, y, deltaX, deltaY } } })); return; } if (wheelAttempts++ >= 119) { wheelScheduled = false; return; } wheelTimer = setTimeout(settleWheel, 16); }); };`,
    "      const wheel = (event) => { if (!event.isTrusted || wheelScheduled) return; wheelScheduled = true; wheelAttempts = 0; settleWheel(); };",
    "      window.addEventListener('pointermove', pointer, { capture: true, passive: true }); window.addEventListener('click', click, true); window.addEventListener('wheel', wheel, { capture: true, passive: true });",
    `      globalThis[\${JSON.stringify(pointerFlushKey)}] = flushPointer; globalThis[\${JSON.stringify(cleanupKey)}] = () => { flushPointer(); window.removeEventListener('pointermove', pointer, true); window.removeEventListener('click', click, true); window.removeEventListener('wheel', wheel, true); if (wheelRaf !== undefined) cancelAnimationFrame(wheelRaf); if (wheelTimer !== undefined) clearTimeout(wheelTimer); delete globalThis[\${JSON.stringify(pointerFlushKey)}]; delete globalThis[\${JSON.stringify(cleanupKey)}]; };`,
    `      debug(\${JSON.stringify(marker)}, JSON.stringify({ kind: 'ready', nonce }));`,
    "    })()`;",
    "    let evaluated; try { evaluated = await session.send('Runtime.evaluate', { expression, contextId: executionContextId, awaitPromise: false, returnByValue: true }); } catch (error) { if (!scopeCurrent()) { retireObserved(executionContextId); await cleanupRetiredObserved(); return; } throw error; }",
    "    if (evaluated?.exceptionDetails !== undefined) throw new Error('recordly isolated observer evaluation failed');",
    "    if (!scopeCurrent()) { retireObserved(executionContextId); await cleanupRetiredObserved(); return; }",
    "    scope.evalDone = true;",
    "    observedContextId = executionContextId;",
    "    activeObservedContexts.add(executionContextId);",
    "    commitObservedReady(document, readiness, scope, executionContextId);",
    "  };",
    "  const activateObserved = (document) => { targetObservedDocument = document; const scope = replaceObservedScope(document); retireActiveObserved(); const readiness = beginObservedGeneration(); retireObserved(observedContextId); observedContextId = undefined; return queueObservation(() => installObserved(document, readiness, scope)); };",
    "  const invalidateObserved = () => { ++observationGeneration; state.observedReady = false; observedReadiness = undefined; targetObservedDocument = undefined; committedObserved = undefined; replaceObservedScope(undefined); retireActiveObserved(); retireObserved(observedContextId); observedContextId = undefined; };",
    "  const flushActiveObserved = async () => { const contextId = observedContextId; try { await flushObserved(contextId); } catch (error) { if (!staleExecutionContext(error)) throw error; } };",
    "  const settleObserved = async () => { await flushActiveObserved(); invalidateObserved(); await observationTail; await cleanupRetiredObserved(); };",
    "  const directString = (value) => value !== null && typeof value === 'object' && value.type === 'string' && typeof value.value === 'string' && !Object.hasOwn(value, 'objectId') && !Object.hasOwn(value, 'unserializableValue');",
    "  const observedListener = (message) => {",
    "    if (!state.active || message.type !== 'debug' || !Array.isArray(message.args) || message.args.length !== 2) return;",
    "    const marker = message.args[0]; const payload = message.args[1];",
    "    if (!directString(marker) || observedScope === undefined || marker.value !== observedScope.marker) return;",
    "    if (!directString(payload) || payload.value.length > 4096) { failObserved(new Error('recordly observed-event console payload malformed')); return; }",
    "    let envelope; try { envelope = JSON.parse(payload.value); } catch (error) { failObserved(error); return; }",
    "    const keys = envelope !== null && typeof envelope === 'object' && !Array.isArray(envelope) ? Object.keys(envelope) : [];",
    "    if (keys.length === 2 && envelope.kind === 'ready' && typeof envelope.nonce === 'string' && /^[0-9a-f]{64}$/u.test(envelope.nonce)) {",
    "      if (observedScope.pinnedNonce === undefined) observedScope.pinnedNonce = envelope.nonce; else if (observedScope.pinnedNonce !== envelope.nonce) return;",
    "      observedScope.readyHandshake = true;",
    "      if (observedReadiness !== undefined && committedObserved === undefined) commitObservedReady(observedScope.identity, observedReadiness, observedScope, observedContextId);",
    "      return;",
    "    }",
    "    if (keys.length !== 3 || envelope.kind !== 'event' || typeof envelope.nonce !== 'string' || !/^[0-9a-f]{64}$/u.test(envelope.nonce) || envelope.event === null || typeof envelope.event !== 'object' || Array.isArray(envelope.event)) { failObserved(new Error('recordly observed-event envelope malformed')); return; }",
    "    if (!state.observedReady) { failObserved(new Error('recordly observed-event arrived before readiness')); return; }",
    "    if (committedObserved === undefined || committedObserved.ready !== true || observedScope.pinnedNonce !== envelope.nonce) return;",
    "    void observedBinding(envelope.event).catch(() => undefined);",
    "  };",
    "  const navigationListener = (message) => {",
    "    if (!state.active || message.frame?.parentId !== undefined) return;",
    "    const document = frameDocument(message.frame);",
    "    if (document === undefined) { if (observationArmed) failObserved(new Error('recordly main-frame document identity unavailable')); return; }",
    "    if (!observationArmed) { targetObservedDocument = document; return; }",
    "    if (sameDocument(document, targetObservedDocument)) return;",
    "    targetObservedDocument = document;",
    "    const scope = replaceObservedScope(document); retireActiveObserved();",
    "    retireObserved(observedContextId); const readiness = beginObservedGeneration();",
    "    observedContextId = undefined;",
    "    void queueObservation(async () => {",
    "      if (!observationCurrent(readiness)) return;",
    "      await cleanupRetiredObserved();",
    "      if (!observationCurrent(readiness)) return;",
    "      await installObserved(document, readiness, scope);",
    "    }).catch((error) => { failObserved(error); });",
    "  };",
    "  const listener = (frame) => {",
    "    if (!state.active) return;",
    "    state.receivedFrames += 1;",
    "    if (state.pending.length >= 120) { state.rejectedFrames += 1; failObserved(new Error('recordly pending-frame limit exceeded')); return; }",
    "    const task = (async () => {",
    "      const result = await post('/frame', { sessionId: recordingSessionId, url: page.url(), frame }, state.token);",
    "      state.acceptedFrames += 1;",
    "      if (state.acceptedFrames === 1) {",
    "        const tree = await session.send('Page.getFrameTree');",
    "        const document = frameDocument(tree.frameTree?.frame);",
    "        if (document === undefined) throw new Error('recordly main-frame document identity unavailable');",
    "        observationArmed = true;",
    "        await activateObserved(document);",
    "      }",
    "      if (result.degrade === true && !state.degraded) {",
    "        state.degraded = true;",
    "        await session.send('Page.startScreencast', { format: 'jpeg', quality: 63, maxWidth: 1152, maxHeight: 720 });",
    "      }",
    "      await session.send('Page.screencastFrameAck', { sessionId: frame.sessionId });",
    "      state.ackedFrames += 1;",
    "    })().catch((error) => { state.rejectedFrames += 1; failObserved(error); });",
    "    state.pending.push(task);",
    "    void task.finally(() => { state.pending = state.pending.filter((item) => item !== task); });",
    "  };",
    "  session.on('Runtime.consoleAPICalled', observedListener);",
    "  session.on('Page.frameNavigated', navigationListener);",
    "  session.on('Page.screencastFrame', listener);",
    "  try {",
    "    await session.send('Page.enable');",
    "    await session.send('Runtime.enable');",
    "    await session.send('Page.startScreencast', { format: 'jpeg', quality: 90, maxWidth: 1440, maxHeight: 900 });",
    "    await Promise.race([initialObservedReady, page.waitForTimeout(10000).then(() => { throw new Error('recordly observed-event readiness timed out'); })]);",
    "  } catch (error) {",
    "    state.active = false;",
    "    state.observedReady = false;",
    "    session.off('Page.screencastFrame', listener);",
    "    session.off('Runtime.consoleAPICalled', observedListener);",
    "    session.off('Page.frameNavigated', navigationListener);",
    "    invalidateObserved();",
    "    await boundedTeardown(() => observationTail).catch(() => undefined);",
    "    await boundedTeardown(() => cleanupRetiredObserved()).catch(() => undefined);",
    "    await boundedTeardown(() => session.send('Page.stopScreencast')).catch(() => undefined);",
    "    await boundedTeardown(() => session.detach()).catch(() => undefined);",
    "    await boundedTeardown(() => post('/fail', { sessionId: recordingSessionId, url: page.url() }, token)).catch(() => undefined);",
    "    throw error;",
    "  }",
    "  page[stateKey] = { session, state, listener, observedListener, navigationListener, settleObserved, post, endpoint, recordingSessionId };",
    "  return { status: 'running', observedReady: true };",
    "}",
    "",
  ].join("\n");
}

export function browserStopHelper(input: BrowserHelperInput): string {
  const stateKey = `__recordlyCapture_${input.sessionId}`;
  return [
    "async (page) => {",
    requestCode(input),
    `  const stateKey = ${JSON.stringify(stateKey)};`,
    "  const capture = page[stateKey];",
    "  if (capture === undefined || capture.recordingSessionId !== recordingSessionId) throw new Error('recordly capture is not active');",
    "  capture.session.off('Page.screencastFrame', capture.listener);",
    "  capture.session.off('Page.frameNavigated', capture.navigationListener);",
    "  await capture.settleObserved().catch(() => { capture.state.observedFailed = true; });",
    "  capture.state.active = false;",
    "  capture.state.observedReady = false;",
    "  capture.session.off('Runtime.consoleAPICalled', capture.observedListener);",
    "  await Promise.all(capture.state.pending);",
    "  await Promise.allSettled(capture.state.observedPending);",
    "  await capture.session.send('Page.stopScreencast');",
    "  if (typeof capture.state.token !== 'string') throw new Error('recordly capture token is unavailable');",
    "  const result = await post('/stop', {",
    "    sessionId: recordingSessionId,",
    "    url: page.url(),",
    "    receivedFrames: capture.state.receivedFrames,",
    "    acceptedFrames: capture.state.acceptedFrames,",
    "    ackedFrames: capture.state.ackedFrames,",
    "    rejectedFrames: capture.state.rejectedFrames,",
    "    degradationRequested: capture.state.degraded,",
    "    observedEventFailure: capture.state.observedFailed,",
    "  }, capture.state.token);",
    "  delete page[stateKey];",
    "  return result;",
    "}",
    "",
  ].join("\n");
}
